clear;

pizza = @(t,x,k,Tr) k*(Tr-x);

[t,y] = ode45(pizza, ...
                     [0 60], ...
                     200,...
                     odeset,...
                     0.08,...
                     18);

plot(t, y,'-o');