clear;

uni = @(t,x,p,q,r) p*x - q*x - r *x;

[t,y] = ode45(uni, ...
                     [2017 2030], ...
                     1000,...
                     odeset,...
                     0.27,...
                     0.00,...
                     0.25);

plot(t, y,'-o');